version: '3.7'

networks:
  datalake:
    external: true

services:
  hadoop-datanode1:
    image: khs920210/hadoop:1.0
    container_name: hadoop-datanode1
    hostname: hadoop-datanode1
    ports:
      - 8042:8042
      - 9864:9864
    tty: true
    stdin_open: true
    networks:
      - datalake
  hadoop-datanode2:
    image: khs920210/hadoop:1.0
    container_name: hadoop-datanode2
    hostname: hadoop-datanode2
    ports:
      - 8043:8042
      - 9865:9864
    tty: true
    stdin_open: true
    networks:
      - datalake
  hadoop-namenode:
    image: khs920210/hadoop:1.0
    container_name: hadoop-namenode
    hostname: hadoop-namenode
    ports:
      - 9870:9870
      - 9000:9000
      - 8088:8088
    tty: true
    stdin_open: true
    networks:
      - datalake
    depends_on:
      - hadoop-datanode1
      - hadoop-datanode2